version: 0.2

env:
variables:
BRANCH_NAME: "develop"
MAJOR_VERSION: "1"
MINOR_VERSION: "0"

parameter-store:

phases:
install:
commands:
      - apt-get update -y && apt-get install -y git
pre_build:
commands:
      - echo "machine git-codecommit.us-east-1.amazonaws.com" >> ~/.netrc
      - echo "login $GIT_USER" >> ~/.netrc
      - echo "password $GIT_PASS" >> ~/.netrc
      - git clone -b $BRANCH_NAME $GIT_REPO
build:
commands:      
      - mvn clean package
      - cd ucxtest-javaproject
      - bash git_taging.sh
post_build:
commands:
      - echo Build completed on `date`
artifacts:
files:
    - 'target/*'
discard-paths: yes
